<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mauricio Garcia">

<title>Stock Market &amp; Cryptocurrency Relationships</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script type="text/javascript" src="https://inst-fs-iad-prod.inscloudgate.net/lp7Z1YOEfEGlsgwwq3rX93ZS6aL9EgULxdnVa6LZjd4Tn50Cz8O_WQq5Vk6Gw8AM-198HnJzqHSVmdUd-lSbBg=="></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Stock Market &amp; Cryptocurrency Relationships</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mauricio Garcia </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("tidyquant")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("dplyr")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("lubridate")</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("tidyr")</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ggplot2")</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("quarto")</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyquant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyquant' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'xts' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'PerformanceAnalytics' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyquant packages ──────────────────────── tidyquant 1.0.9 ──
✔ PerformanceAnalytics 2.0.8      ✔ TTR                  0.24.4
✔ quantmod             0.4.26     ✔ xts                  0.14.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyquant_conflicts() ──
✖ zoo::as.Date()                 masks base::as.Date()
✖ zoo::as.Date.numeric()         masks base::as.Date.numeric()
✖ PerformanceAnalytics::legend() masks graphics::legend()
✖ quantmod::summary()            masks base::summary()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
######################### Warning from 'xts' package ##########################
#                                                                             #
# The dplyr lag() function breaks how base R's lag() function is supposed to  #
# work, which breaks lag(my_xts). Calls to lag(my_xts) that you type or       #
# source() into this session won't work correctly.                            #
#                                                                             #
# Use stats::lag() to make sure you're not using dplyr::lag(), or you can add #
# conflictRules('dplyr', exclude = 'lag') to your .Rprofile to stop           #
# dplyr from breaking base R's lag() function.                                #
#                                                                             #
# Code in packages is not affected. It's protected by R's namespace mechanism #
# Set `options(xts.warn_dplyr_breaks_lag = FALSE)` to suppress this warning.  #
#                                                                             #
###############################################################################

Attaching package: 'dplyr'

The following objects are masked from 'package:xts':

    first, last

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lubridate'

The following objects are masked from 'package:base':

    date, intersect, setdiff, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)     <span class="co"># VIF</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)   <span class="co"># cross-validation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'caret' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines) <span class="co"># splines</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="stock-market-cryptocurrency-analysis" class="level2">
<h2 class="anchored" data-anchor-id="stock-market-cryptocurrency-analysis">Stock Market &amp; Cryptocurrency Analysis</h2>
<p>In this project, I will analyze the relationships between the stock market and cryptocurrency markets, focusing on how they interact and influence each other. Specifically, I will explore whether cryptocurrency returns (Bitcoin and Ethereum) correlate with the returns of a widely used stock market benchmark, the SPY ETF, which tracks the S&amp;P 500 index.</p>
<p>The dataset consists of daily data from 2017-11-09 to 2024-12-10, covering key variables such as daily closing prices, high and low prices, trading volumes, and smoothed prices (average of high and low). This timeframe was chosen because it captures significant cryptocurrency adoption milestones while ensuring consistent data availability for all assets.</p>
<p>The outcome variable of interest is daily return of BTC (we will be analyzing ETH as well, see hypothesis section for more), representing the percentage change in Bitcoin’s value from one day to the next. Predictors &amp; variables include, but not limited to:</p>
<ul>
<li>Returns of Bitcoin and Ethereum (numeric variables).</li>
<li>Prices of these three assets (numeric variables).</li>
<li>The day of the week (a categorical variable) to examine potential weekday effects.</li>
<li>Trading volumes for Bitcoin, Ethereum, and SPY to explore correlations (numeric variables).</li>
</ul>
</section>
<section id="personal-motivations-interest" class="level2">
<h2 class="anchored" data-anchor-id="personal-motivations-interest">Personal Motivations &amp; Interest</h2>
<p>I conducted this analysis for two main reasons:</p>
<ol type="1">
<li><p><u><strong>Personal Experience:</strong></u> I am fairly active in both the stock and cryptocurrency markets. Naturally, many questions arise about the potential connections between these two markets, and I want to explore those relationships.</p></li>
<li><p><u><strong>Helping Others Transition:</strong></u> I know many people who are interested in getting started with trading in either the stock or cryptocurrency markets. Some are more familiar with one market than the other—most people are generally more accustomed to the stock market, as it is more established. I want this analysis to serve as a helpful resource for anyone looking to make the transition from one market to the other. Additionally, since my target audience includes beginners or those with little technical experience, I will be providing thorough explanations to ensure clarity.</p></li>
</ol>
</section>
<section id="important-terms-to-know" class="level2">
<h2 class="anchored" data-anchor-id="important-terms-to-know">Important Terms to Know</h2>
<p>If you’re not familiar with the stock or cryptocurrency markets, here are some important terms to know:</p>
<ol type="1">
<li><p><strong>Market capitalization:</strong></p>
<ul>
<li><p>Market capitalization, often referred to as “market cap,” is the total market value of an asset or company. It is calculated by multiplying the current price by the total number of outstanding shares or coins.</p></li>
<li><p>Market cap is a key measure of an asset’s size and perceived stability in comparison to others.</p></li>
</ul></li>
<li><p><strong>Volume</strong>:</p>
<ul>
<li><p>Volume measures the total amount of an asset traded over a given time period. High volume often indicates strong investor interest or market activity, whereas low volume might signal indecision or a lack of engagement.</p></li>
<li><p>In this analysis, volume can help explore relationships between market activity in SPY, Bitcoin, and Ethereum.</p></li>
</ul></li>
<li><p><strong>Daily Return</strong>:</p>
<ul>
<li>The daily return is the percentage change in an asset’s price from one day to the next.</li>
</ul></li>
<li><p><strong>ETF (Exchange-Traded Fund)</strong>:</p>
<ul>
<li><p>An ETF is a pooled investment security that tracks an index, sector, commodity, or asset, and can be traded on an exchange like a stock.</p></li>
<li><p>SPY is an ETF that mirrors the performance of the S&amp;P 500 Index, making it a common benchmark for the U.S. stock market.</p></li>
</ul></li>
</ol>
</section>
<section id="origins-of-dataset-and-its-construction" class="level2">
<h2 class="anchored" data-anchor-id="origins-of-dataset-and-its-construction">Origins of Dataset and its Construction</h2>
<p>For this analysis, I’ll be looking at the very well-known SPY, which tracks the S&amp;P 500, a broad representation of the American stock market. SPY is an ETF that is diversified across many sectors, offering exposure to a wide range of large-cap U.S. companies.</p>
<p>As for cryptocurrency, I’ll be looking at the two cryptocurrencies with the biggest market capitalizations as of 12/11/2024: Bitcoin (~$1.93T) and Ethereum (~$442B). Bitcoin has consistently held the #1 spot since its creation in 2009, and Ethereum has held the #2 spot since its launch in 2015, with only very minor, temporary fluctuations in their rankings (e.g., XRP occasionally surpassing Ethereum during market rallies most notably during December 2017 - January 2018).</p>
<p>I used the Yahoo Finance API to get data on the stock market and cryptocurrency. We will be analyzing data from 11/09/2017 (because this is when Ethereum data becomes readily available via Yahoo Finance API) to 12/10/2024 (day this paper was worked on). There are a total of 2.589 observations, covering all three assets.</p>
<section id="bitcoin-api-call" class="level3">
<h3 class="anchored" data-anchor-id="bitcoin-api-call">Bitcoin API Call</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calls Yahoo Finance API and gets Bitcoin data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>crypto_btc_data <span class="ot">&lt;-</span> <span class="fu">tq_get</span>(<span class="st">"BTC-USD"</span>, <span class="at">from =</span> <span class="st">"2017-11-09"</span>, <span class="at">to =</span> <span class="st">"2024-12-10"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crypto_btc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  symbol  date        open  high   low close     volume adjusted
  &lt;chr&gt;   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
1 BTC-USD 2017-11-09 7447. 7447. 7102. 7144. 3226249984    7144.
2 BTC-USD 2017-11-10 7174. 7312  6437. 6618. 5208249856    6618.
3 BTC-USD 2017-11-11 6619. 6873. 6204. 6358. 4908680192    6358.
4 BTC-USD 2017-11-12 6295. 6625. 5519. 5950. 8957349888    5950.
5 BTC-USD 2017-11-13 5938. 6811. 5844. 6559. 6263249920    6559.
6 BTC-USD 2017-11-14 6561. 6765. 6462. 6636. 3197110016    6636.</code></pre>
</div>
</div>
</section>
<section id="ethereum-api-call" class="level3">
<h3 class="anchored" data-anchor-id="ethereum-api-call">Ethereum API Call</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>crypto_eth_data <span class="ot">&lt;-</span> <span class="fu">tq_get</span>(<span class="st">"ETH-USD"</span>, <span class="at">from =</span> <span class="st">"2017-11-09"</span>, <span class="at">to =</span> <span class="st">"2024-12-10"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crypto_eth_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  symbol  date        open  high   low close     volume adjusted
  &lt;chr&gt;   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
1 ETH-USD 2017-11-09  309.  329.  307.  321.  893249984     321.
2 ETH-USD 2017-11-10  321.  325.  295.  299.  885985984     299.
3 ETH-USD 2017-11-11  299.  319.  298.  315.  842300992     315.
4 ETH-USD 2017-11-12  315.  319.  299.  308. 1613479936     308.
5 ETH-USD 2017-11-13  307.  328.  307.  317. 1041889984     317.
6 ETH-USD 2017-11-14  317.  340.  317.  338. 1069680000     338.</code></pre>
</div>
</div>
</section>
<section id="spy-api-call" class="level3">
<h3 class="anchored" data-anchor-id="spy-api-call">SPY API Call</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>spy_data <span class="ot">&lt;-</span> <span class="fu">tq_get</span>(<span class="st">"SPY"</span>, <span class="at">from =</span> <span class="st">"2017-11-09"</span>, <span class="at">to =</span> <span class="st">"2024-12-10"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(spy_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 8
  symbol date        open  high   low close   volume adjusted
  &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 SPY    2017-11-09  258.  258.  256.  258. 95085500     230.
2 SPY    2017-11-10  258.  258.  257.  258. 59984700     230.
3 SPY    2017-11-13  257.  259.  257.  258. 50228600     230.
4 SPY    2017-11-14  257.  258.  257.  258. 61315200     230.
5 SPY    2017-11-15  257.  257.  256.  256. 80811500     229.
6 SPY    2017-11-16  258.  259.  257.  259. 67777000     231.</code></pre>
</div>
</div>
</section>
</section>
<section id="preprocessing-cleaning-data" class="level2">
<h2 class="anchored" data-anchor-id="preprocessing-cleaning-data">Preprocessing &amp; Cleaning Data</h2>
<section id="checking-for-missing-values" class="level3">
<h3 class="anchored" data-anchor-id="checking-for-missing-values">Checking for Missing Values</h3>
<p>We will check for NaN (missing) values before combining any of these three datasets, ensuring we have no NaN values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check for NaN values</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(spy_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(crypto_btc_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(crypto_eth_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>There are no missing values in any of the three datasets.</p>
</section>
<section id="accounting-for-different-opening-closing-times" class="level3">
<h3 class="anchored" data-anchor-id="accounting-for-different-opening-closing-times">Accounting for Different Opening &amp; Closing Times</h3>
<p>A problem I faced very early on was: which price do I look at for this analysis? Close, open, etc? Would this even matter much? For reference, the stock market is open from 9:30am to 4pm (EST) and cryptocurrencies can be traded 24/7. Due to this difference in trading hours, categories such as volume (lower time frame for SPY), close, open, high and low do not match up regarding time. In the grand scheme of things, this could alter results slightly because we are evaluating these prices at different times. To avoid this, I decided to smooth the prices by taking the average of both the high and the low. I chose both these columns because high and low are not time-sensitive (as these can happen at any time of the day).</p>
<section id="smoothing-via-averaging-the-highs-and-lows-of-btc-eth-spy" class="level4">
<h4 class="anchored" data-anchor-id="smoothing-via-averaging-the-highs-and-lows-of-btc-eth-spy">Smoothing via averaging the highs and lows of BTC, ETH, &amp; SPY</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>spy_data <span class="ot">&lt;-</span> spy_data <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">smoothed_price =</span> (high <span class="sc">+</span> low) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>crypto_btc_data <span class="ot">&lt;-</span> crypto_btc_data <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">smoothed_price =</span> (high <span class="sc">+</span> low) <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>crypto_eth_data <span class="ot">&lt;-</span> crypto_eth_data <span class="sc">%&gt;%</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">smoothed_price =</span> (high <span class="sc">+</span> low) <span class="sc">/</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="verify-if-smoothed_price-column-was-made-successfully" class="level4">
<h4 class="anchored" data-anchor-id="verify-if-smoothed_price-column-was-made-successfully">Verify if smoothed_price column was made successfully</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(spy_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  symbol date        open  high   low close   volume adjusted smoothed_price
  &lt;chr&gt;  &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;
1 SPY    2017-11-09  258.  258.  256.  258. 95085500     230.           257.
2 SPY    2017-11-10  258.  258.  257.  258. 59984700     230.           258.
3 SPY    2017-11-13  257.  259.  257.  258. 50228600     230.           258.
4 SPY    2017-11-14  257.  258.  257.  258. 61315200     230.           257.
5 SPY    2017-11-15  257.  257.  256.  256. 80811500     229.           256.
6 SPY    2017-11-16  258.  259.  257.  259. 67777000     231.           258.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crypto_btc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  symbol  date        open  high   low close     volume adjusted smoothed_price
  &lt;chr&gt;   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;
1 BTC-USD 2017-11-09 7447. 7447. 7102. 7144. 3226249984    7144.          7274.
2 BTC-USD 2017-11-10 7174. 7312  6437. 6618. 5208249856    6618.          6874.
3 BTC-USD 2017-11-11 6619. 6873. 6204. 6358. 4908680192    6358.          6539.
4 BTC-USD 2017-11-12 6295. 6625. 5519. 5950. 8957349888    5950.          6072.
5 BTC-USD 2017-11-13 5938. 6811. 5844. 6559. 6263249920    6559.          6328.
6 BTC-USD 2017-11-14 6561. 6765. 6462. 6636. 3197110016    6636.          6613.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crypto_eth_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  symbol  date        open  high   low close     volume adjusted smoothed_price
  &lt;chr&gt;   &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;
1 ETH-USD 2017-11-09  309.  329.  307.  321.  893249984     321.           318.
2 ETH-USD 2017-11-10  321.  325.  295.  299.  885985984     299.           310.
3 ETH-USD 2017-11-11  299.  319.  298.  315.  842300992     315.           309.
4 ETH-USD 2017-11-12  315.  319.  299.  308. 1613479936     308.           309.
5 ETH-USD 2017-11-13  307.  328.  307.  317. 1041889984     317.           318.
6 ETH-USD 2017-11-14  317.  340.  317.  338. 1069680000     338.           328.</code></pre>
</div>
</div>
</section>
</section>
<section id="combining-the-three-datasets-into-one" class="level3">
<h3 class="anchored" data-anchor-id="combining-the-three-datasets-into-one">Combining the three datasets into one</h3>
<section id="ensure-that-all-three-datasets-have-the-same-columns-for-smooth-combination" class="level4">
<h4 class="anchored" data-anchor-id="ensure-that-all-three-datasets-have-the-same-columns-for-smooth-combination">Ensure that all three datasets have the same columns for smooth combination</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check columns in each dataset</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(spy_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "symbol"         "date"           "open"           "high"          
[5] "low"            "close"          "volume"         "adjusted"      
[9] "smoothed_price"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(crypto_btc_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "symbol"         "date"           "open"           "high"          
[5] "low"            "close"          "volume"         "adjusted"      
[9] "smoothed_price"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(crypto_eth_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "symbol"         "date"           "open"           "high"          
[5] "low"            "close"          "volume"         "adjusted"      
[9] "smoothed_price"</code></pre>
</div>
</div>
</section>
<section id="combine-the-datasets" class="level4">
<h4 class="anchored" data-anchor-id="combine-the-datasets">Combine the datasets</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># combine the datasets by aligning them on the date column</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> <span class="fu">full_join</span>(spy_data, crypto_btc_data, <span class="at">by =</span> <span class="st">"date"</span>, <span class="at">suffix =</span> <span class="fu">c</span>(<span class="st">"_spy"</span>, <span class="st">"_btc"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">full_join</span>(crypto_eth_data, <span class="at">by =</span> <span class="st">"date"</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="co"># add the "_eth" suffix to its columns</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(combined_data)[<span class="fu">names</span>(combined_data) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"open"</span>, <span class="st">"high"</span>, <span class="st">"low"</span>, <span class="st">"close"</span>, <span class="st">"volume"</span>, <span class="st">"adjusted"</span>, <span class="st">"smoothed_price"</span>)] <span class="ot">&lt;-</span> </span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="fu">c</span>(<span class="st">"open"</span>, <span class="st">"high"</span>, <span class="st">"low"</span>, <span class="st">"close"</span>, <span class="st">"volume"</span>, <span class="st">"adjusted"</span>, <span class="st">"smoothed_price"</span>), <span class="st">"_eth"</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a><span class="co"># verify the full join was successful</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(combined_data)  <span class="co"># check structure</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [2,589 × 25] (S3: tbl_df/tbl/data.frame)
 $ symbol_spy        : chr [1:2589] "SPY" "SPY" "SPY" "SPY" ...
 $ date              : Date[1:2589], format: "2017-11-09" "2017-11-10" ...
 $ open_spy          : num [1:2589] 258 258 257 257 257 ...
 $ high_spy          : num [1:2589] 258 258 259 258 257 ...
 $ low_spy           : num [1:2589] 256 257 257 257 256 ...
 $ close_spy         : num [1:2589] 258 258 258 258 256 ...
 $ volume_spy        : num [1:2589] 95085500 59984700 50228600 61315200 80811500 ...
 $ adjusted_spy      : num [1:2589] 230 230 230 230 229 ...
 $ smoothed_price_spy: num [1:2589] 257 258 258 257 256 ...
 $ symbol_btc        : chr [1:2589] "BTC-USD" "BTC-USD" "BTC-USD" "BTC-USD" ...
 $ open_btc          : num [1:2589] 7447 7174 5938 6561 6635 ...
 $ high_btc          : num [1:2589] 7447 7312 6811 6765 7342 ...
 $ low_btc           : num [1:2589] 7102 6437 5844 6462 6635 ...
 $ close_btc         : num [1:2589] 7144 6618 6559 6636 7316 ...
 $ volume_btc        : num [1:2589] 3.23e+09 5.21e+09 6.26e+09 3.20e+09 4.20e+09 ...
 $ adjusted_btc      : num [1:2589] 7144 6618 6559 6636 7316 ...
 $ smoothed_price_btc: num [1:2589] 7274 6874 6328 6613 6989 ...
 $ symbol            : chr [1:2589] "ETH-USD" "ETH-USD" "ETH-USD" "ETH-USD" ...
 $ open_eth          : num [1:2589] 309 321 307 317 338 ...
 $ high_eth          : num [1:2589] 329 325 328 340 341 ...
 $ low_eth           : num [1:2589] 307 295 307 317 330 ...
 $ close_eth         : num [1:2589] 321 299 317 338 333 ...
 $ volume_eth        : num [1:2589] 8.93e+08 8.86e+08 1.04e+09 1.07e+09 7.23e+08 ...
 $ adjusted_eth      : num [1:2589] 321 299 317 338 333 ...
 $ smoothed_price_eth: num [1:2589] 318 310 318 328 335 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(combined_data)  <span class="co"># check first few rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 25
  symbol_spy date       open_spy high_spy low_spy close_spy volume_spy
  &lt;chr&gt;      &lt;date&gt;        &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1 SPY        2017-11-09     258.     258.    256.      258.   95085500
2 SPY        2017-11-10     258.     258.    257.      258.   59984700
3 SPY        2017-11-13     257.     259.    257.      258.   50228600
4 SPY        2017-11-14     257.     258.    257.      258.   61315200
5 SPY        2017-11-15     257.     257.    256.      256.   80811500
6 SPY        2017-11-16     258.     259.    257.      259.   67777000
# ℹ 18 more variables: adjusted_spy &lt;dbl&gt;, smoothed_price_spy &lt;dbl&gt;,
#   symbol_btc &lt;chr&gt;, open_btc &lt;dbl&gt;, high_btc &lt;dbl&gt;, low_btc &lt;dbl&gt;,
#   close_btc &lt;dbl&gt;, volume_btc &lt;dbl&gt;, adjusted_btc &lt;dbl&gt;,
#   smoothed_price_btc &lt;dbl&gt;, symbol &lt;chr&gt;, open_eth &lt;dbl&gt;, high_eth &lt;dbl&gt;,
#   low_eth &lt;dbl&gt;, close_eth &lt;dbl&gt;, volume_eth &lt;dbl&gt;, adjusted_eth &lt;dbl&gt;,
#   smoothed_price_eth &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(combined_data)  <span class="co"># check column names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "symbol_spy"         "date"               "open_spy"          
 [4] "high_spy"           "low_spy"            "close_spy"         
 [7] "volume_spy"         "adjusted_spy"       "smoothed_price_spy"
[10] "symbol_btc"         "open_btc"           "high_btc"          
[13] "low_btc"            "close_btc"          "volume_btc"        
[16] "adjusted_btc"       "smoothed_price_btc" "symbol"            
[19] "open_eth"           "high_eth"           "low_eth"           
[22] "close_eth"          "volume_eth"         "adjusted_eth"      
[25] "smoothed_price_eth"</code></pre>
</div>
</div>
</section>
<section id="remove-redundant-columns-such-as-symbol" class="level4">
<h4 class="anchored" data-anchor-id="remove-redundant-columns-such-as-symbol">Remove redundant columns such as symbol</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>symbol_spy, <span class="sc">-</span>symbol_btc, <span class="sc">-</span>symbol)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># verify all three symbol columns were removed</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [2,589 × 22] (S3: tbl_df/tbl/data.frame)
 $ date              : Date[1:2589], format: "2017-11-09" "2017-11-10" ...
 $ open_spy          : num [1:2589] 258 258 257 257 257 ...
 $ high_spy          : num [1:2589] 258 258 259 258 257 ...
 $ low_spy           : num [1:2589] 256 257 257 257 256 ...
 $ close_spy         : num [1:2589] 258 258 258 258 256 ...
 $ volume_spy        : num [1:2589] 95085500 59984700 50228600 61315200 80811500 ...
 $ adjusted_spy      : num [1:2589] 230 230 230 230 229 ...
 $ smoothed_price_spy: num [1:2589] 257 258 258 257 256 ...
 $ open_btc          : num [1:2589] 7447 7174 5938 6561 6635 ...
 $ high_btc          : num [1:2589] 7447 7312 6811 6765 7342 ...
 $ low_btc           : num [1:2589] 7102 6437 5844 6462 6635 ...
 $ close_btc         : num [1:2589] 7144 6618 6559 6636 7316 ...
 $ volume_btc        : num [1:2589] 3.23e+09 5.21e+09 6.26e+09 3.20e+09 4.20e+09 ...
 $ adjusted_btc      : num [1:2589] 7144 6618 6559 6636 7316 ...
 $ smoothed_price_btc: num [1:2589] 7274 6874 6328 6613 6989 ...
 $ open_eth          : num [1:2589] 309 321 307 317 338 ...
 $ high_eth          : num [1:2589] 329 325 328 340 341 ...
 $ low_eth           : num [1:2589] 307 295 307 317 330 ...
 $ close_eth         : num [1:2589] 321 299 317 338 333 ...
 $ volume_eth        : num [1:2589] 8.93e+08 8.86e+08 1.04e+09 1.07e+09 7.23e+08 ...
 $ adjusted_eth      : num [1:2589] 321 299 317 338 333 ...
 $ smoothed_price_eth: num [1:2589] 318 310 318 328 335 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "date"               "open_spy"           "high_spy"          
 [4] "low_spy"            "close_spy"          "volume_spy"        
 [7] "adjusted_spy"       "smoothed_price_spy" "open_btc"          
[10] "high_btc"           "low_btc"            "close_btc"         
[13] "volume_btc"         "adjusted_btc"       "smoothed_price_btc"
[16] "open_eth"           "high_eth"           "low_eth"           
[19] "close_eth"          "volume_eth"         "adjusted_eth"      
[22] "smoothed_price_eth"</code></pre>
</div>
</div>
</section>
</section>
<section id="adding-useful-variables" class="level3">
<h3 class="anchored" data-anchor-id="adding-useful-variables">Adding useful variables</h3>
<section id="add-day_of_week-categorical-variable" class="level4">
<h4 class="anchored" data-anchor-id="add-day_of_week-categorical-variable">Add “day_of_week” categorical variable</h4>
<p>Each day is associated with a weekday (7 categories: Sun–Sat), allowing us to analyze ~370 observations per day of the week.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add the day of the week under "day_of_week"</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">%&gt;%</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">day_of_week =</span> <span class="fu">wday</span>(date, <span class="at">label =</span> <span class="cn">TRUE</span>))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="co"># verify if "day_of_week" column is present</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 23
  date       open_spy high_spy low_spy close_spy volume_spy adjusted_spy
  &lt;date&gt;        &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;
1 2017-11-09     258.     258.    256.      258.   95085500         230.
2 2017-11-10     258.     258.    257.      258.   59984700         230.
3 2017-11-13     257.     259.    257.      258.   50228600         230.
4 2017-11-14     257.     258.    257.      258.   61315200         230.
5 2017-11-15     257.     257.    256.      256.   80811500         229.
6 2017-11-16     258.     259.    257.      259.   67777000         231.
# ℹ 16 more variables: smoothed_price_spy &lt;dbl&gt;, open_btc &lt;dbl&gt;,
#   high_btc &lt;dbl&gt;, low_btc &lt;dbl&gt;, close_btc &lt;dbl&gt;, volume_btc &lt;dbl&gt;,
#   adjusted_btc &lt;dbl&gt;, smoothed_price_btc &lt;dbl&gt;, open_eth &lt;dbl&gt;,
#   high_eth &lt;dbl&gt;, low_eth &lt;dbl&gt;, close_eth &lt;dbl&gt;, volume_eth &lt;dbl&gt;,
#   adjusted_eth &lt;dbl&gt;, smoothed_price_eth &lt;dbl&gt;, day_of_week &lt;ord&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [2,589 × 23] (S3: tbl_df/tbl/data.frame)
 $ date              : Date[1:2589], format: "2017-11-09" "2017-11-10" ...
 $ open_spy          : num [1:2589] 258 258 257 257 257 ...
 $ high_spy          : num [1:2589] 258 258 259 258 257 ...
 $ low_spy           : num [1:2589] 256 257 257 257 256 ...
 $ close_spy         : num [1:2589] 258 258 258 258 256 ...
 $ volume_spy        : num [1:2589] 95085500 59984700 50228600 61315200 80811500 ...
 $ adjusted_spy      : num [1:2589] 230 230 230 230 229 ...
 $ smoothed_price_spy: num [1:2589] 257 258 258 257 256 ...
 $ open_btc          : num [1:2589] 7447 7174 5938 6561 6635 ...
 $ high_btc          : num [1:2589] 7447 7312 6811 6765 7342 ...
 $ low_btc           : num [1:2589] 7102 6437 5844 6462 6635 ...
 $ close_btc         : num [1:2589] 7144 6618 6559 6636 7316 ...
 $ volume_btc        : num [1:2589] 3.23e+09 5.21e+09 6.26e+09 3.20e+09 4.20e+09 ...
 $ adjusted_btc      : num [1:2589] 7144 6618 6559 6636 7316 ...
 $ smoothed_price_btc: num [1:2589] 7274 6874 6328 6613 6989 ...
 $ open_eth          : num [1:2589] 309 321 307 317 338 ...
 $ high_eth          : num [1:2589] 329 325 328 340 341 ...
 $ low_eth           : num [1:2589] 307 295 307 317 330 ...
 $ close_eth         : num [1:2589] 321 299 317 338 333 ...
 $ volume_eth        : num [1:2589] 8.93e+08 8.86e+08 1.04e+09 1.07e+09 7.23e+08 ...
 $ adjusted_eth      : num [1:2589] 321 299 317 338 333 ...
 $ smoothed_price_eth: num [1:2589] 318 310 318 328 335 ...
 $ day_of_week       : Ord.factor w/ 7 levels "Sun"&lt;"Mon"&lt;"Tue"&lt;..: 5 6 2 3 4 5 6 2 3 4 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "date"               "open_spy"           "high_spy"          
 [4] "low_spy"            "close_spy"          "volume_spy"        
 [7] "adjusted_spy"       "smoothed_price_spy" "open_btc"          
[10] "high_btc"           "low_btc"            "close_btc"         
[13] "volume_btc"         "adjusted_btc"       "smoothed_price_btc"
[16] "open_eth"           "high_eth"           "low_eth"           
[19] "close_eth"          "volume_eth"         "adjusted_eth"      
[22] "smoothed_price_eth" "day_of_week"       </code></pre>
</div>
</div>
</section>
<section id="add-a-daily-return-column-for-spy-bitcoin-and-ethereum" class="level4">
<h4 class="anchored" data-anchor-id="add-a-daily-return-column-for-spy-bitcoin-and-ethereum">Add a daily return column for SPY, Bitcoin, and Ethereum</h4>
<p>Returns (A.K.A. percentages, and not absolute prices) are the standard way to measure and compare asset performance in finance. They allow for a <strong>normalized comparison</strong> across assets with different price levels. For instance:</p>
<ul>
<li>A $10 price increase is a bigger deal for Ethereum (price ~$300) than for Bitcoin (price ~$30,000). Returns express this change in percentage terms, making them directly comparable.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">spy_return =</span> (close_spy <span class="sc">-</span> <span class="fu">lag</span>(close_spy)) <span class="sc">/</span> <span class="fu">lag</span>(close_spy),</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">btc_return =</span> (close_btc <span class="sc">-</span> <span class="fu">lag</span>(close_btc)) <span class="sc">/</span> <span class="fu">lag</span>(close_btc),</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">eth_return =</span> (close_eth <span class="sc">-</span> <span class="fu">lag</span>(close_eth)) <span class="sc">/</span> <span class="fu">lag</span>(close_eth)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()  <span class="co"># remove rows with NA values caused by lag</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 26
  date       open_spy high_spy low_spy close_spy volume_spy adjusted_spy
  &lt;date&gt;        &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;
1 2017-11-10     258.     258.    257.      258.   59984700         230.
2 2017-11-13     257.     259.    257.      258.   50228600         230.
3 2017-11-14     257.     258.    257.      258.   61315200         230.
4 2017-11-15     257.     257.    256.      256.   80811500         229.
5 2017-11-16     258.     259.    257.      259.   67777000         231.
6 2017-11-17     258.     259.    258.      258.   75756800         230.
# ℹ 19 more variables: smoothed_price_spy &lt;dbl&gt;, open_btc &lt;dbl&gt;,
#   high_btc &lt;dbl&gt;, low_btc &lt;dbl&gt;, close_btc &lt;dbl&gt;, volume_btc &lt;dbl&gt;,
#   adjusted_btc &lt;dbl&gt;, smoothed_price_btc &lt;dbl&gt;, open_eth &lt;dbl&gt;,
#   high_eth &lt;dbl&gt;, low_eth &lt;dbl&gt;, close_eth &lt;dbl&gt;, volume_eth &lt;dbl&gt;,
#   adjusted_eth &lt;dbl&gt;, smoothed_price_eth &lt;dbl&gt;, day_of_week &lt;ord&gt;,
#   spy_return &lt;dbl&gt;, btc_return &lt;dbl&gt;, eth_return &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [1,780 × 26] (S3: tbl_df/tbl/data.frame)
 $ date              : Date[1:1780], format: "2017-11-10" "2017-11-13" ...
 $ open_spy          : num [1:1780] 258 257 257 257 258 ...
 $ high_spy          : num [1:1780] 258 259 258 257 259 ...
 $ low_spy           : num [1:1780] 257 257 257 256 257 ...
 $ close_spy         : num [1:1780] 258 258 258 256 259 ...
 $ volume_spy        : num [1:1780] 59984700 50228600 61315200 80811500 67777000 ...
 $ adjusted_spy      : num [1:1780] 230 230 230 229 231 ...
 $ smoothed_price_spy: num [1:1780] 258 258 257 256 258 ...
 $ open_btc          : num [1:1780] 7174 5938 6561 6635 7323 ...
 $ high_btc          : num [1:1780] 7312 6811 6765 7342 7967 ...
 $ low_btc           : num [1:1780] 6437 5844 6462 6635 7177 ...
 $ close_btc         : num [1:1780] 6618 6559 6636 7316 7872 ...
 $ volume_btc        : num [1:1780] 5.21e+09 6.26e+09 3.20e+09 4.20e+09 5.12e+09 ...
 $ adjusted_btc      : num [1:1780] 6618 6559 6636 7316 7872 ...
 $ smoothed_price_btc: num [1:1780] 6874 6328 6613 6989 7572 ...
 $ open_eth          : num [1:1780] 321 307 317 338 333 ...
 $ high_eth          : num [1:1780] 325 328 340 341 336 ...
 $ low_eth           : num [1:1780] 295 307 317 330 324 ...
 $ close_eth         : num [1:1780] 299 317 338 333 331 ...
 $ volume_eth        : num [1:1780] 8.86e+08 1.04e+09 1.07e+09 7.23e+08 7.97e+08 ...
 $ adjusted_eth      : num [1:1780] 299 317 338 333 331 ...
 $ smoothed_price_eth: num [1:1780] 310 318 328 335 330 ...
 $ day_of_week       : Ord.factor w/ 7 levels "Sun"&lt;"Mon"&lt;"Tue"&lt;..: 6 2 3 4 5 6 2 3 4 6 ...
 $ spy_return        : num [1:1780] -0.00031 0.00093 -0.00232 -0.00501 0.0085 ...
 $ btc_return        : num [1:1780] -0.07355 -0.00886 0.01163 0.10244 0.07602 ...
 $ eth_return        : num [1:1780] -0.0674 0.0584 0.066 -0.0127 -0.0073 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "date"               "open_spy"           "high_spy"          
 [4] "low_spy"            "close_spy"          "volume_spy"        
 [7] "adjusted_spy"       "smoothed_price_spy" "open_btc"          
[10] "high_btc"           "low_btc"            "close_btc"         
[13] "volume_btc"         "adjusted_btc"       "smoothed_price_btc"
[16] "open_eth"           "high_eth"           "low_eth"           
[19] "close_eth"          "volume_eth"         "adjusted_eth"      
[22] "smoothed_price_eth" "day_of_week"        "spy_return"        
[25] "btc_return"         "eth_return"        </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="hypothesis-question-formulation" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-question-formulation">Hypothesis / Question Formulation</h2>
<ol type="1">
<li><p><strong>Bitcoin follows stock movements</strong></p>
<ul>
<li><p><em>Informal Hypothesis:</em> On average, Bitcoin returns increase as SPY (stock market) returns increase.</p></li>
<li><p><em>Statistical Hypothesis:</em></p>
<ul>
<li><p><em>H0 (Null Hypothesis):</em> The coefficient on SPY returns in a model predicting Bitcoin returns is zero, meaning SPY returns have no effect on Bitcoin returns.</p></li>
<li><p><em>HA (Alternative Hypothesis):</em> The coefficient on SPY returns is greater than zero, meaning higher SPY returns are associated with higher Bitcoin returns.</p></li>
</ul></li>
</ul></li>
<li><p><strong>Crypto and stock returns are highest and lowest on the same weekdays</strong></p>
<ul>
<li><em>Informal Hypothesis:</em> The best (highest returns) and worst (lowest returns) performing weekdays align for both SPY and Bitcoin/Ethereum.</li>
<li><em>Statistical Approach:</em> Examine average returns by weekday for SPY and crypto. If patterns match, we have evidence in support of this hypothesis.</li>
</ul></li>
<li><p><strong>Crypto and stock trading volumes are correlated</strong></p>
<ul>
<li><p><em>Informal Hypothesis:</em> High Bitcoin volume often coincides with high SPY volume. Similarly, low volumes in both might occur together, indicating shared market sentiment.</p></li>
<li><p><em>Statistical Approach:</em> Check the correlation between volumes (volume_spy, volume_btc, volume_eth). If significant positive correlation, it suggests simultaneous volume surges.</p></li>
</ul></li>
<li><p><strong>Is the famous Monday effect real for the stock market, and does it affect cryptocurrency?</strong></p>
<ul>
<li><em>Informal Hypothesis:</em> If the Monday effect (traditionally lower returns on Mondays) exists for SPY, we test if a similar pattern appears in Bitcoin and Ethereum returns.</li>
<li><em>Statistical Approach:</em> Compare mean returns on Mondays vs.&nbsp;other days for both SPY and cryptos.</li>
</ul></li>
</ol>
</section>
<section id="exploring-visualizing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-visualizing-the-data">Exploring &amp; Visualizing the Data</h2>
<section id="btc-return-vs.-predictors" class="level3">
<h3 class="anchored" data-anchor-id="btc-return-vs.-predictors">BTC Return vs.&nbsp;Predictors</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries if not already loaded</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(combined_data, <span class="fu">aes</span>(<span class="at">x =</span> spy_return, <span class="at">y =</span> btc_return)) <span class="sc">+</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"BTC Return vs. SPY Return"</span>,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"SPY Return"</span>,</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"BTC Return"</span></span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(combined_data, <span class="fu">aes</span>(<span class="at">x =</span> eth_return, <span class="at">y =</span> btc_return)) <span class="sc">+</span></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"BTC Return vs. Ethereum Return"</span>,</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"ETH Return"</span>,</span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"BTC Return"</span></span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb70-20"><a href="#cb70-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-21"><a href="#cb70-21" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On the left plot, the points are fairly concentrated around zero for both SPY and BTC returns, indicating that most daily returns cluster around small positive or negative percentages. There’s a fitted linear regression line in blue, which appears to slope upwards, but the relationship is relatively weak. The points are scattered widely around the line, suggesting that while there might be a slight positive relationship, SPY returns do not strongly explain BTC returns.</p>
<p>On the right, daily BTC returns are plotted against daily ETH returns. The points form a tighter diagonal cloud, and the fitted line in dark green is clearly steeper and more aligned with the bulk of the points. This suggests a stronger positive relationship between BTC and ETH returns compared to the BTC-SPY relationship. In other words, when Ethereum’s returns are positive, Bitcoin’s returns also tend to be positive, and vice versa.</p>
<p>Overall, the visualization highlights that while there might be some correlation with SPY (traditional stock market), Bitcoin seems more closely related to Ethereum returns. This is consistent with the expectation that two cryptocurrencies might move together more strongly than a cryptocurrency and a stock market proxy.</p>
</section>
<section id="average-returns-by-day-of-the-week" class="level3">
<h3 class="anchored" data-anchor-id="average-returns-by-day-of-the-week"><strong>Average Returns by Day of the Week</strong></h3>
<p>We will use boxplots to compare the average returns of SPY, Bitcoin, and Ethereum for each day of the week. This can help us assess whether there are patterns in returns based on weekdays. SPY cannot be traded on the weekends hence why the boxplot excludes weekends. Cryptocurrency can be traded 24/7.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SPY Returns</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined_data, <span class="fu">aes</span>(<span class="at">x =</span> day_of_week, <span class="at">y =</span> spy_return)) <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"SPY Returns by Day of the Week (Excluding Weekends)"</span>, </span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Day of the Week"</span>, <span class="at">y =</span> <span class="st">"SPY Returns"</span>) <span class="sc">+</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In this boxplot we can see there is not much clearly visible difference between the days. There are some clear outliers on Monday, Tuesday, and Friday. We will now look at the mean returns by weekday in number form instead to see if we can draw any insights from that.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate mean returns by weekday</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>spy_mean_returns <span class="ot">&lt;-</span> combined_data <span class="sc">%&gt;%</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(day_of_week) <span class="sc">%&gt;%</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_return =</span> <span class="fu">mean</span>(spy_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_return =</span> <span class="fu">sd</span>(spy_return, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))  <span class="co"># include standard deviation</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(spy_mean_returns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  day_of_week mean_return sd_return
  &lt;ord&gt;             &lt;dbl&gt;     &lt;dbl&gt;
1 Mon            0.000559    0.0133
2 Tue            0.000764    0.0116
3 Wed            0.000562    0.0116
4 Thu            0.000421    0.0126
5 Fri            0.000455    0.0120</code></pre>
</div>
</div>
<p>From this we can see that there is still not much difference. The “Monday effect” is a market anomaly where stock prices often decline significantly after the weekend. As we can see here, the lowest mean return is Thursday. This dataset clearly does not confirm this. Instead, Monday shows positive mean returns, and Tuesday has the highest average performance. This may suggest that:</p>
<ul>
<li>The “Monday effect” may not be present in this selected timeframe.</li>
<li>Modern markets may have mitigated historical day-of-the-week patterns due to factors like algorithmic trading or after-hours news digestion.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recalculate day_of_week &amp; returns for original cryptos</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>crypto_btc_data <span class="ot">&lt;-</span> crypto_btc_data <span class="sc">%&gt;%</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">day_of_week =</span> <span class="fu">wday</span>(date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">week_start =</span> <span class="dv">1</span>))</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>crypto_eth_data <span class="ot">&lt;-</span> crypto_eth_data <span class="sc">%&gt;%</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">day_of_week =</span> <span class="fu">wday</span>(date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">week_start =</span> <span class="dv">1</span>))</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>crypto_btc_data <span class="ot">&lt;-</span> crypto_btc_data <span class="sc">%&gt;%</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">btc_return =</span> (close <span class="sc">-</span> <span class="fu">lag</span>(close)) <span class="sc">/</span> <span class="fu">lag</span>(close)) <span class="sc">%&gt;%</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.finite</span>(btc_return))  <span class="co"># Filter non-finite values</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>crypto_eth_data <span class="ot">&lt;-</span> crypto_eth_data <span class="sc">%&gt;%</span></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">eth_return =</span> (close <span class="sc">-</span> <span class="fu">lag</span>(close)) <span class="sc">/</span> <span class="fu">lag</span>(close)) <span class="sc">%&gt;%</span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.finite</span>(eth_return))  <span class="co"># Filter non-finite values</span></span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Bitcoin Returns graph</span></span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(crypto_btc_data, <span class="fu">aes</span>(<span class="at">x =</span> day_of_week, <span class="at">y =</span> btc_return)) <span class="sc">+</span></span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"orange"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Bitcoin Returns by Day of the Week (Including Weekends)"</span>, </span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Day of the Week"</span>, <span class="at">y =</span> <span class="st">"Bitcoin Returns"</span>) <span class="sc">+</span></span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-25"><a href="#cb76-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Ethereum Returns graph</span></span>
<span id="cb76-26"><a href="#cb76-26" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(crypto_eth_data, <span class="fu">aes</span>(<span class="at">x =</span> day_of_week, <span class="at">y =</span> eth_return)) <span class="sc">+</span></span>
<span id="cb76-27"><a href="#cb76-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb76-28"><a href="#cb76-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Ethereum Returns by Day of the Week (Including Weekends)"</span>, </span>
<span id="cb76-29"><a href="#cb76-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Day of the Week"</span>, <span class="at">y =</span> <span class="st">"Ethereum Returns"</span>) <span class="sc">+</span></span>
<span id="cb76-30"><a href="#cb76-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb76-31"><a href="#cb76-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-32"><a href="#cb76-32" aria-hidden="true" tabindex="-1"></a>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># grid.arrange(p1, p2, ncol = 2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The Monday effect, typically observed in traditional markets, is not reflected in the cryptocurrency boxplots. Furthermore, the average returns appear relatively consistent across all days of the week. However, Wednesday shows slightly higher returns within the upper bounds of its boxplot, suggesting potential outperformance on this day compared to others.</p>
</section>
<section id="volume-correlations" class="level3">
<h3 class="anchored" data-anchor-id="volume-correlations">Volume Correlations</h3>
<p>We can test the hypothesis: <strong>Crypto and stock trading volumes are correlated.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation matrix for volumes</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>volume_corr <span class="ot">&lt;-</span> combined_data <span class="sc">%&gt;%</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(volume_spy, volume_btc, volume_eth) <span class="sc">%&gt;%</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(volume_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             volume_spy   volume_btc  volume_eth
volume_spy  1.000000000 -0.001710383 -0.05154015
volume_btc -0.001710383  1.000000000  0.85909757
volume_eth -0.051540151  0.859097574  1.00000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scatterplots for volume relationships</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined_data, <span class="fu">aes</span>(<span class="at">x =</span> volume_spy, <span class="at">y =</span> volume_btc)) <span class="sc">+</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"SPY vs. Bitcoin Volume"</span>, <span class="at">x =</span> <span class="st">"SPY Volume"</span>, <span class="at">y =</span> <span class="st">"Bitcoin Volume"</span>) <span class="sc">+</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(combined_data, <span class="fu">aes</span>(<span class="at">x =</span> volume_spy, <span class="at">y =</span> volume_eth)) <span class="sc">+</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"SPY vs. Ethereum Volume"</span>, <span class="at">x =</span> <span class="st">"SPY Volume"</span>, <span class="at">y =</span> <span class="st">"Ethereum Volume"</span>) <span class="sc">+</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The results from the correlation matrix and scatterplots can address the hypothesis that crypto and stock trading volumes might be correlated. Specifically, if high volume in Bitcoin or Ethereum coincides with high volume in SPY, it might indicate shared market sentiment or simultaneous interest across both markets.</p>
<p><strong>Observations from the Correlation Matrix:</strong></p>
<ul>
<li><p><strong>SPY &amp; Bitcoin Volumes:</strong> The correlation is approximately -0.0017, which is effectively zero. This suggests that increases in SPY trading volume do not coincide with predictable increases (or decreases) in Bitcoin volume.</p></li>
<li><p><strong>SPY &amp; Ethereum Volumes:</strong> The correlation is about -0.0515, still very close to zero. Again, there’s no strong indication that when SPY volume is high, Ethereum volume is also high (or low).</p></li>
<li><p><strong>Bitcoin &amp; Ethereum Volumes:</strong> Here we see a strong positive correlation of about 0.86. This indicates that Bitcoin and Ethereum volumes tend to move together, which might reflect a common investor base or simultaneous interest in the crypto market.</p></li>
</ul>
<p>These findings suggest that while cryptocurrencies (Bitcoin and Ethereum) are closely linked to each other in terms of trading activity, their volumes are not moving in tandem with SPY. In other words, stock market trading volume (as measured by SPY) does not appear to be a reliable indicator of how active the crypto markets will be on any given day.</p>
<p><strong>Caveat:</strong></p>
<p>It’s important to note that SPY is just one ETF representing the S&amp;P 500 index, not the entire stock market. It’s possible that different segments of the equity market, or other asset classes, might show different relationships with crypto volumes.</p>
</section>
<section id="price-trends-over-time" class="level3">
<h3 class="anchored" data-anchor-id="price-trends-over-time">Price Trends Over Time</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># approximate supply values from December 2024</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>supply_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Asset =</span> <span class="fu">c</span>(<span class="st">"SPY"</span>, <span class="st">"Bitcoin"</span>, <span class="st">"Ethereum"</span>),</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Supply =</span> <span class="fu">c</span>(<span class="fl">930e6</span>, <span class="fl">19.5e6</span>, <span class="fl">120e6</span>) <span class="co"># SPY in shares, BTC, and ETH in coins</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a><span class="co"># create market cap from smoothed prices</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>smoothed_prices <span class="ot">&lt;-</span> combined_data <span class="sc">%&gt;%</span></span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(date, smoothed_price_spy, smoothed_price_btc, smoothed_price_eth) <span class="sc">%&gt;%</span></span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"smoothed_price"</span>), </span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"Asset"</span>, </span>
<span id="cb83-12"><a href="#cb83-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"Smoothed_Price"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb83-13"><a href="#cb83-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Asset =</span> <span class="fu">case_when</span>(</span>
<span id="cb83-14"><a href="#cb83-14" aria-hidden="true" tabindex="-1"></a>    Asset <span class="sc">==</span> <span class="st">"smoothed_price_spy"</span> <span class="sc">~</span> <span class="st">"SPY"</span>,</span>
<span id="cb83-15"><a href="#cb83-15" aria-hidden="true" tabindex="-1"></a>    Asset <span class="sc">==</span> <span class="st">"smoothed_price_btc"</span> <span class="sc">~</span> <span class="st">"Bitcoin"</span>,</span>
<span id="cb83-16"><a href="#cb83-16" aria-hidden="true" tabindex="-1"></a>    Asset <span class="sc">==</span> <span class="st">"smoothed_price_eth"</span> <span class="sc">~</span> <span class="st">"Ethereum"</span></span>
<span id="cb83-17"><a href="#cb83-17" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb83-18"><a href="#cb83-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(supply_data, <span class="at">by =</span> <span class="st">"Asset"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb83-19"><a href="#cb83-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Market_Cap =</span> Smoothed_Price <span class="sc">*</span> Supply)</span>
<span id="cb83-20"><a href="#cb83-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-21"><a href="#cb83-21" aria-hidden="true" tabindex="-1"></a><span class="co"># plot scaled by market cap</span></span>
<span id="cb83-22"><a href="#cb83-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(smoothed_prices, <span class="fu">aes</span>(<span class="at">x =</span> date, <span class="at">y =</span> Market_Cap, <span class="at">color =</span> Asset)) <span class="sc">+</span></span>
<span id="cb83-23"><a href="#cb83-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb83-24"><a href="#cb83-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Market Cap Trends Over Time"</span>,</span>
<span id="cb83-25"><a href="#cb83-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>, <span class="at">y =</span> <span class="st">"Market Capitalization"</span>,</span>
<span id="cb83-26"><a href="#cb83-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Asset"</span>) <span class="sc">+</span></span>
<span id="cb83-27"><a href="#cb83-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This graph gives uses our smoothed prices with the current circulating supply and shares outstanding for these assets. It gives us a beautiful graph that showcases the outstanding, unusual growth of cryptocurrencies and the stability of SPY.</p>
</section>
</section>
<section id="fitting-the-first-multiple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-first-multiple-linear-regression-model">Fitting the first Multiple Linear Regression Model</h2>
<p>Let’s start with a multiple linear regression model predicting btc_return from spy_return, volume_spy, and day_of_week.</p>
<p>Model:</p>
<ul>
<li>btc_return ~ spy_return + volume_spy + volume_btc + day_of_week</li>
</ul>
<p>This model examines the relationship between Bitcoin returns and the U.S. stock market (via SPY returns), along with Bitcoin’s own trading volume and the volume of SPY (which may reflect overall market participation), as well as day-of-week patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(btc_return <span class="sc">~</span> spy_return <span class="sc">+</span> volume_spy <span class="sc">+</span> volume_btc <span class="sc">+</span> day_of_week, <span class="at">data =</span> combined_data)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = btc_return ~ spy_return + volume_spy + volume_btc + 
    day_of_week, data = combined_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.27723 -0.01911 -0.00180  0.01816  0.25085 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    2.090e-03  2.687e-03   0.778    0.437    
spy_return     9.378e-01  8.420e-02  11.138   &lt;2e-16 ***
volume_spy    -1.533e-11  2.497e-11  -0.614    0.539    
volume_btc     3.973e-14  4.867e-14   0.816    0.414    
day_of_week.L -2.667e-03  2.283e-03  -1.168    0.243    
day_of_week.Q  1.749e-03  2.254e-03   0.776    0.438    
day_of_week.C  3.300e-04  2.233e-03   0.148    0.883    
day_of_week^4  3.013e-03  2.222e-03   1.356    0.175    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0423 on 1772 degrees of freedom
Multiple R-squared:  0.07253,   Adjusted R-squared:  0.06887 
F-statistic:  19.8 on 7 and 1772 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Key Points:</strong></p>
<ul>
<li><p><strong>Overall Model Significance:</strong></p>
<ul>
<li>The F-statistic is approximately 19.8 with a p-value &lt; 2.2e-16. This means that as a group, the predictors in the model are significantly related to btc_return. In other words, the model is capturing some statistically significant relationships, even if modest.</li>
</ul></li>
<li><p><strong>R-squared:</strong></p>
<ul>
<li><p>Multiple R-squared: 0.07253 (~7.25%)</p></li>
<li><p>Adjusted R-squared: 0.06887 (~6.89%)</p></li>
<li><p>This suggests that the model explains around 7% of the variation in Bitcoin returns. While statistically significant, the practical explanatory power is quite low. Markets are complex, and returns are influenced by many factors not captured here.</p></li>
</ul></li>
<li><p><strong>Coefficients:</strong></p>
<ul>
<li><p><strong>Intercept:</strong> Estimate is 0.00209, not significant (p=0.437). This implies that when all predictors are at their baseline (and for the reference day_of_week), the expected BTC return doesn’t differ significantly from zero.</p></li>
<li><p><strong>SPY Return:</strong> Estimate = 0.9378 with p &lt; 2e-16. This is strongly significant and suggests that when SPY return increases by 1 unit (100%), BTC return increases on average by about 0.94 units. Of course, SPY returns are usually much smaller than 100%, so practically, a small positive change in SPY return corresponds to a smaller but still positive expected change in BTC return.</p></li>
<li><p><strong>Volume Variables (SPY and BTC):</strong></p>
<ul>
<li><p>SPY Volume coefficient: -1.53e-11, p=0.539</p></li>
<li><p>BTC Volume coefficient: 3.97e-14, p=0.414<br>
Both are not statistically significant. This indicates that for this dataset, variations in daily trading volume (of SPY or BTC) do not have a clear linear relationship with daily BTC returns once we account for SPY returns and day_of_week.</p></li>
</ul></li>
<li><p><strong>day_of_week:</strong><br>
The day_of_week variable is represented in polynomial contrasts (L, Q, C, ^4, etc.), which can make interpretation less direct. None of these terms are significant (all p-values &gt; 0.1). This suggests no strong day-of-week pattern in BTC returns after controlling for SPY returns and volumes.</p></li>
<li><p>Practically, it means that once we consider SPY returns, neither volumes nor the day of the week seem to offer much additional explanatory power for BTC returns in this model.</p></li>
</ul></li>
<li><p><strong>Residual Standard Error (RSE):</strong> 0.0423</p>
<ul>
<li>The RSE gives a sense of how much actual BTC returns differ from the model’s predictions. An RSE of about 0.0423 means the typical deviation between predicted and actual BTC return is about 4.23 percentage points per day. Given daily returns are often small percentages, this is not negligible—it shows predictions are still quite rough.</li>
</ul></li>
<li><p><strong>Interpretation and Implications:</strong></p>
<ul>
<li><p>The strong and positive coefficient on <strong>spy_return</strong> supports the idea that BTC returns have some relationship to stock market movements represented by SPY. It doesn’t mean BTC is fully explained by SPY returns, but there’s a noticeable positive association.</p></li>
<li><p>Volumes and day_of_week didn’t significantly contribute to the model, suggesting these factors might not be linear predictors of BTC returns or their effects are overshadowed by other unmodeled factors.</p></li>
<li><p>The relatively low R² highlights that daily BTC returns are influenced by many other variables not included here, such as crypto-specific news, macroeconomic conditions, investor sentiment, regulatory changes, or global events.</p></li>
</ul></li>
</ul>
<p>In summary, the model shows a statistically significant but weak ability to explain BTC returns. SPY returns appear relevant, but volume and day_of_week effects are minimal in this context.</p>
<section id="diagnostic-checks" class="level3">
<h3 class="anchored" data-anchor-id="diagnostic-checks">Diagnostic Checks</h3>
<p>We will check whether assumptions are met and consider potential improvements if needed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We look for non-random patterns in residuals, non-constant variance, or deviations from normality. If issues arise, we might consider transformations or adding nonlinear terms. Here is a breakdown:</p>
<ul>
<li><p><strong>Residuals vs.&nbsp;Fitted:</strong></p>
<ul>
<li>The points appear roughly centered around zero, with no strong pattern. This suggests the mean-zero residual assumption is reasonably met, though some clustering near zero is expected since returns are small.</li>
</ul></li>
<li><p><strong>Q-Q Plot:</strong></p>
<ul>
<li>The Q-Q plot shows residuals deviating somewhat from the straight line (in the tails). This suggests the residuals are not perfectly normally distributed. From what I could find, this is not uncommon in financial return data (perfect normality is rarely achieved &amp; returns typically have these distributions). Mild deviations from normality are less critical compared to mean-zero residuals and constant variance.</li>
</ul></li>
<li><p><strong>Scale-Location Plot:</strong></p>
<ul>
<li>The spread of residuals seems relatively even, indicating no major heteroscedasticity (no clear pattern of increasing or decreasing variance).</li>
</ul></li>
<li><p><strong>Residuals vs.&nbsp;Leverage:</strong></p>
<ul>
<li>While not perfect, slight deviations could acceptable. A few points have more leverage, but it does not seem like it is something to act upon. There are bigger issues (see next section). There is one evident point at the very right side.</li>
</ul></li>
</ul>
</section>
</section>
<section id="improving-the-model" class="level2">
<h2 class="anchored" data-anchor-id="improving-the-model">Improving the Model</h2>
<p>Although our initial linear regression model showed that SPY returns have a statistically significant relationship with Bitcoin returns, the model explains only about 7% of the variation, leaving much unexplained.</p>
<section id="splines" class="level3">
<h3 class="anchored" data-anchor-id="splines">Splines</h3>
<ol type="1">
<li><p><strong>Nonlinear Relationships:</strong></p>
<ul>
<li>We can try spline terms. For example, if we suspect that the effect of SPY returns on BTC returns diminishes or changes beyond certain thresholds, we can use spline functions.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>model_spline <span class="ot">&lt;-</span> <span class="fu">lm</span>(btc_return <span class="sc">~</span> <span class="fu">bs</span>(spy_return, <span class="at">df=</span><span class="dv">4</span>) <span class="sc">+</span> volume_spy <span class="sc">+</span> volume_btc <span class="sc">+</span> day_of_week, <span class="at">data=</span>combined_data)</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_spline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = btc_return ~ bs(spy_return, df = 4) + volume_spy + 
    volume_btc + day_of_week, data = combined_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.195893 -0.019387 -0.001733  0.017499  0.249955 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -2.400e-01  3.571e-02  -6.721 2.43e-11 ***
bs(spy_return, df = 4)1  1.139e-01  4.837e-02   2.354   0.0187 *  
bs(spy_return, df = 4)2  2.878e-01  4.024e-02   7.152 1.24e-12 ***
bs(spy_return, df = 4)3  2.399e-01  4.229e-02   5.672 1.64e-08 ***
bs(spy_return, df = 4)4  3.085e-01  4.464e-02   6.910 6.74e-12 ***
volume_spy               5.615e-11  3.243e-11   1.731   0.0836 .  
volume_btc               6.259e-14  4.884e-14   1.282   0.2002    
day_of_week.L           -3.573e-03  2.279e-03  -1.568   0.1172    
day_of_week.Q            1.771e-03  2.241e-03   0.790   0.4296    
day_of_week.C           -1.930e-04  2.224e-03  -0.087   0.9309    
day_of_week^4            2.977e-03  2.209e-03   1.347   0.1780    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04206 on 1769 degrees of freedom
Multiple R-squared:  0.08476,   Adjusted R-squared:  0.07959 
F-statistic: 16.38 on 10 and 1769 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model1, model_spline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: btc_return ~ spy_return + volume_spy + volume_btc + day_of_week
Model 2: btc_return ~ bs(spy_return, df = 4) + volume_spy + volume_btc + 
    day_of_week
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1   1772 3.1710                                  
2   1769 3.1292  3   0.04181 7.8788 3.197e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Using ANOVA, we can compare models. It shows an overall improvement because:</p>
<ul>
<li><p>Residual Degrees of Freedom (Res.Df) decreases from 1772 to 1769 (we used 3 extra degrees of freedom for the splines).</p></li>
<li><p>Residual Sum of Squares (RSS) drops from 3.1710 to 3.1292.</p></li>
<li><p>The F-test for the difference in models has a p-value of 3.197e-05 (very small), indicating that adding spline terms for spy_return significantly improves the model fit.</p></li>
<li><p>The nonlinear relationship captured by spline terms better explains the variability in BTC returns than a simple linear term for SPY returns alone.</p></li>
</ul>
<ol start="2" type="1">
<li><strong>Goodness-of-Fit Improvements:</strong>
<ul>
<li><p><strong>Multiple R-squared</strong> increases from about 0.0725 in the original model to about 0.08476 (a bit over 8%) in the spline model.</p></li>
<li><p>The Adjusted R-squared also rises slightly from about 0.0689 to about 0.0796, reflecting a better model fit even after accounting for the additional complexity.</p></li>
<li><p>While these are still relatively small R² values, it’s an improvement, suggesting that BTC returns have a more complex, nonlinear relationship with SPY returns than initially modeled.</p></li>
</ul></li>
<li><strong>Coefficients of Spline Terms:</strong>
<ul>
<li>Each of the spline coefficients (bs(spy_return, df=4)1 through bs(spy_return, df=4)4) is statistically significant. This indicates that the relationship between SPY returns and BTC returns cannot be adequately described by a single straight line. This makes complete sense given the complexities of these markets.</li>
</ul></li>
<li><strong>volume_btc, volume_spy,</strong> and <strong>day_of_week</strong> terms remain non-significant, indicating they do not substantially improve the model’s explanation of BTC returns, even after introducing nonlinearity for SPY returns.</li>
</ol>
<p>By modeling spy_return nonlinearly, we’ve captured a more accurate and richer relationship. Although the overall predictive power remains modest—markets are complex, and many other factors may be at play—the spline model provides evidence that the BTC-SPY relationship is not purely linear. It’s a step toward more sophisticated modeling approaches that can further uncover how traditional markets influence crypto returns.</p>
</section>
<section id="hypothesizing-an-interaction" class="level3">
<h3 class="anchored" data-anchor-id="hypothesizing-an-interaction">Hypothesizing an Interaction</h3>
<section id="polynomial-contrasts" class="level4">
<h4 class="anchored" data-anchor-id="polynomial-contrasts">Polynomial contrasts</h4>
<p>We might suspect that the relationship between SPY returns and BTC returns differs by the day of the week. For instance, perhaps BTC is more sensitive to SPY movements on certain weekdays. To test this, we introduce an interaction term between spy_return and day_of_week:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(btc_return <span class="sc">~</span> spy_return<span class="sc">*</span>day_of_week <span class="sc">+</span> volume_spy <span class="sc">+</span> volume_btc, <span class="at">data =</span> combined_data)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = btc_return ~ spy_return * day_of_week + volume_spy + 
    volume_btc, data = combined_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.241412 -0.019219 -0.001678  0.017691  0.249807 

Coefficients:
                           Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               1.400e-03  2.705e-03   0.517  0.60488    
spy_return                9.338e-01  8.419e-02  11.092  &lt; 2e-16 ***
day_of_week.L            -2.873e-03  2.283e-03  -1.258  0.20843    
day_of_week.Q             1.733e-03  2.253e-03   0.769  0.44192    
day_of_week.C             6.105e-04  2.233e-03   0.273  0.78460    
day_of_week^4             2.961e-03  2.222e-03   1.333  0.18271    
volume_spy               -6.112e-12  2.526e-11  -0.242  0.80882    
volume_btc                3.820e-14  4.865e-14   0.785  0.43248    
spy_return:day_of_week.L  1.659e-01  1.811e-01   0.916  0.35995    
spy_return:day_of_week.Q -8.694e-02  1.842e-01  -0.472  0.63700    
spy_return:day_of_week.C -4.949e-01  1.852e-01  -2.673  0.00759 ** 
spy_return:day_of_week^4 -3.593e-02  1.875e-01  -0.192  0.84806    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04225 on 1768 degrees of freedom
Multiple R-squared:  0.07688,   Adjusted R-squared:  0.07114 
F-statistic: 13.39 on 11 and 1768 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Model: btc_return ~ spy_return*day_of_week + volume_spy + volume_btc</p>
<p>The term spy_return:day_of_week.C is significant (p=0.00759). Polynomial contrasts (L, Q, C, ^4) represent linear, quadratic, cubic, and quartic patterns across the ordered categories. The “C” contrast relates to a cubic pattern in the day_of_week variable.</p>
</section>
<section id="dummy-variables" class="level4">
<h4 class="anchored" data-anchor-id="dummy-variables">Dummy Variables</h4>
<p>I will now try using dummy variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#c onvert day_of_week into a regular factor </span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>combined_data<span class="sc">$</span>day_of_week <span class="ot">&lt;-</span> <span class="fu">factor</span>(combined_data<span class="sc">$</span>day_of_week, <span class="at">ordered =</span> <span class="cn">FALSE</span>)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="co"># check the structure again to confirm it is no longer ordered</span></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(combined_data<span class="sc">$</span>day_of_week)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 5 levels "Mon","Tue","Wed",..: 5 1 2 3 4 5 1 2 3 5 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set Monday as baseline</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>combined_data<span class="sc">$</span>day_of_week <span class="ot">&lt;-</span> <span class="fu">relevel</span>(combined_data<span class="sc">$</span>day_of_week, <span class="at">ref =</span> <span class="st">"Mon"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>model_interaction_dummy <span class="ot">&lt;-</span> <span class="fu">lm</span>(btc_return <span class="sc">~</span> spy_return<span class="sc">*</span>day_of_week <span class="sc">+</span> volume_spy <span class="sc">+</span> volume_btc, <span class="at">data =</span> combined_data)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interaction_dummy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = btc_return ~ spy_return * day_of_week + volume_spy + 
    volume_btc, data = combined_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.241412 -0.019219 -0.001678  0.017691  0.249807 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                4.304e-03  3.345e-03   1.287   0.1983    
spy_return                 9.346e-01  1.779e-01   5.253 1.68e-07 ***
day_of_weekTue            -3.489e-03  3.207e-03  -1.088   0.2768    
day_of_weekWed            -1.707e-03  3.212e-03  -0.531   0.5952    
day_of_weekThu            -6.078e-03  3.225e-03  -1.885   0.0596 .  
day_of_weekFri            -3.247e-03  3.238e-03  -1.003   0.3160    
volume_spy                -6.112e-12  2.526e-11  -0.242   0.8088    
volume_btc                 3.820e-14  4.865e-14   0.785   0.4325    
spy_return:day_of_weekTue -3.259e-01  2.615e-01  -1.246   0.2127    
spy_return:day_of_weekWed  1.986e-02  2.594e-01   0.077   0.9390    
spy_return:day_of_weekThu  4.050e-01  2.492e-01   1.625   0.1043    
spy_return:day_of_weekFri -1.032e-01  2.555e-01  -0.404   0.6862    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04225 on 1768 degrees of freedom
Multiple R-squared:  0.07688,   Adjusted R-squared:  0.07114 
F-statistic: 13.39 on 11 and 1768 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>None of the interaction terms made from day_of_week are statistically significant at the 5% level.</p></li>
<li><p>The main effect of spy_return remains significant and positive, confirming that BTC generally moves with SPY.</p></li>
<li><p>Weekday main effects and interactions do not add much explanatory power either, as all their p-values are well above 0.05.</p></li>
</ul>
</section>
</section>
<section id="comparing-spline-model-vs.-dummy-variable-model" class="level3">
<h3 class="anchored" data-anchor-id="comparing-spline-model-vs.-dummy-variable-model">Comparing Spline Model vs.&nbsp;Dummy Variable Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_spline, model_interaction_dummy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: btc_return ~ bs(spy_return, df = 4) + volume_spy + volume_btc + 
    day_of_week
Model 2: btc_return ~ spy_return * day_of_week + volume_spy + volume_btc
  Res.Df    RSS Df Sum of Sq F Pr(&gt;F)
1   1769 3.1292                      
2   1768 3.1561  1 -0.026937         </code></pre>
</div>
</div>
<p>Here, we use ANOVA to compare the nonlinear model with the interaction model. These are the models:</p>
<ol type="1">
<li><p>Model 1 (nonlinear): btc_return ~ bs(spy_return, df = 4) + volume_spy + volume_btc + day_of_week</p></li>
<li><p>Model 2 (interaction): btc_return ~ spy_return * day_of_week + volume_spy + volume_btc</p></li>
</ol>
<p>The output:</p>
<ul>
<li><p>Residual sum of squares for Model 1 (spline model): 3.1292</p></li>
<li><p>Residual sum of squares for Model 2 (interaction model): 3.1561</p></li>
</ul>
<p>The interaction model has a slightly larger RSS, meaning it actually fits the data worse than the spline model. The F-test does not favor the interaction model.</p>
<p><strong>Takeaways:</strong></p>
<ol type="1">
<li><p>Since none of the interaction terms are significant, adding them does not meaningfully improve the model’s explanatory power.</p></li>
<li><p>The comparison with the spline model shows that the spline model (nonlinear terms for SPY returns) provides a better fit than the interaction model.</p></li>
<li><p>In simpler terms, while introducing spline terms helped capture a more nuanced (nonlinear) relationship between SPY and BTC returns, trying to vary that relationship by day_of_week did not help. BTC’s sensitivity to SPY returns does not appear to differ substantially across weekdays in this dataset.</p></li>
</ol>
<p>Using simple spline terms is the winner here and it is better avoid day-of-week interactions.</p>
</section>
</section>
<section id="testing-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="testing-hypotheses">Testing Hypotheses</h2>
<p>There were several hypotheses and questions at the start. Some we have already addressed, but I will do so more explicitly in this section. Now that we have fitted and improved models, we can test these hypotheses using statistical procedures.</p>
<p>Note: These have been proven above.</p>
<ul>
<li><p><strong>Hypothesis 1:</strong> Bitcoin follows stock movements</p>
<ol type="1">
<li><p>H0: The coefficient on SPY returns in a model predicting BTC returns is zero.</p></li>
<li><p>HA: The coefficient on SPY returns is greater than zero (positive relationship).</p></li>
</ol></li>
</ul>
<p>In our final spline model, spy_return is significant and positive. We reject H0 and conclude that BTC returns increase as SPY returns increase, supporting HA.</p>
<ul>
<li><p><strong>Hypothesis 2:</strong> Crypto and stock returns are highest and lowest on the same weekdays</p>
<ol type="1">
<li><p>H0: There is no alignment in best/worst weekdays between SPY and BTC.</p></li>
<li><p>HA: Best and worst-performing weekdays align for both SPY and BTC.</p></li>
</ol></li>
</ul>
<p>No significant weekday pattern emerged for either SPY or BTC. We fail to reject H0 in this context, meaning we found no evidence that the best/worst days match.</p>
<ul>
<li><p><strong>Hypothesis 3:</strong> Crypto and stock trading volumes (SPY) are correlated</p>
<ol type="1">
<li><p>H0: No correlation between SPY volume and crypto volumes.</p></li>
<li><p>HA: A positive correlation exists between SPY volume and crypto volumes.</p></li>
</ol></li>
</ul>
<p>Near-zero correlation between SPY and crypto volumes. We fail to reject H0, as there is no evidence of a meaningful correlation.</p>
<ul>
<li><p><strong>Hypothesis 4:</strong> Is the Monday effect real for the stock market, and does it affect cryptocurrency?</p>
<ol type="1">
<li><p>H0: Monday returns do not differ from other weekdays for SPY or BTC.</p></li>
<li><p>HA: Monday returns are significantly different (lower) than other weekdays.</p></li>
</ol></li>
</ul>
<p>No significant Monday effect observed for SPY or BTC returns. We fail to reject H0; no Monday effect was detected.</p>
</section>
<section id="assessing-the-robustness-of-conclusions" class="level2">
<h2 class="anchored" data-anchor-id="assessing-the-robustness-of-conclusions">Assessing the Robustness of Conclusions</h2>
<section id="autoplot-observation" class="level3">
<h3 class="anchored" data-anchor-id="autoplot-observation">Autoplot Observation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(model_spline) <span class="co"># best model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(model1) <span class="co"># original model</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looking at both my first model and best model, There is one point at the very right which is highly influential and an outlier observation with high leverage. Such a point might correspond to an unusual market event; a day with extreme BTC or SPY returns.</p>
<p>A point may have high leverage if its predictor values (e.g., SPY return) are far from the bulk of the data. In financial returns, and in the context of the stock and crypto markets, this could be an especially volatile day. High leverage points can disproportionately affect regression coefficients.</p>
</section>
<section id="influence-of-deleting-high-leverage-observation" class="level3">
<h3 class="anchored" data-anchor-id="influence-of-deleting-high-leverage-observation">Influence of Deleting High Leverage Observation</h3>
<p>First, we have to find it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute Cook's distances for all points in the model_spline</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>cooks_dist <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(model_spline)</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a><span class="co"># find the index of the observation with the highest Cook's distance</span></span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>inf_idx <span class="ot">&lt;-</span> <span class="fu">which.max</span>(cooks_dist)</span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>inf_idx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>588 
588 </code></pre>
</div>
</div>
<p>Now that we have the index, we will target it, remove it, and I will re-fit my best model (spline) without it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>data_noinf <span class="ot">&lt;-</span> combined_data[<span class="sc">-</span>inf_idx, ]</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="co"># re-fit the model without that observation</span></span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>model_spline_noinf <span class="ot">&lt;-</span> <span class="fu">lm</span>(btc_return <span class="sc">~</span> <span class="fu">bs</span>(spy_return, <span class="at">df=</span><span class="dv">4</span>) <span class="sc">+</span> volume_spy <span class="sc">+</span> volume_btc <span class="sc">+</span> day_of_week,</span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> data_noinf)</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_spline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = btc_return ~ bs(spy_return, df = 4) + volume_spy + 
    volume_btc + day_of_week, data = combined_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.195893 -0.019387 -0.001733  0.017499  0.249955 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -2.400e-01  3.571e-02  -6.721 2.43e-11 ***
bs(spy_return, df = 4)1  1.139e-01  4.837e-02   2.354   0.0187 *  
bs(spy_return, df = 4)2  2.878e-01  4.024e-02   7.152 1.24e-12 ***
bs(spy_return, df = 4)3  2.399e-01  4.229e-02   5.672 1.64e-08 ***
bs(spy_return, df = 4)4  3.085e-01  4.464e-02   6.910 6.74e-12 ***
volume_spy               5.615e-11  3.243e-11   1.731   0.0836 .  
volume_btc               6.259e-14  4.884e-14   1.282   0.2002    
day_of_week.L           -3.573e-03  2.279e-03  -1.568   0.1172    
day_of_week.Q            1.771e-03  2.241e-03   0.790   0.4296    
day_of_week.C           -1.930e-04  2.224e-03  -0.087   0.9309    
day_of_week^4            2.977e-03  2.209e-03   1.347   0.1780    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04206 on 1769 degrees of freedom
Multiple R-squared:  0.08476,   Adjusted R-squared:  0.07959 
F-statistic: 16.38 on 10 and 1769 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_spline_noinf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = btc_return ~ bs(spy_return, df = 4) + volume_spy + 
    volume_btc + day_of_week, data = data_noinf)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.192145 -0.018981 -0.001721  0.017532  0.250398 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -3.371e-01  3.819e-02  -8.827  &lt; 2e-16 ***
bs(spy_return, df = 4)1  2.787e-01  4.724e-02   5.901 4.33e-09 ***
bs(spy_return, df = 4)2  3.500e-01  4.123e-02   8.488  &lt; 2e-16 ***
bs(spy_return, df = 4)3  3.684e-01  4.467e-02   8.248 3.10e-16 ***
bs(spy_return, df = 4)4  3.990e-01  4.617e-02   8.642  &lt; 2e-16 ***
volume_spy               5.195e-11  3.224e-11   1.612   0.1072    
volume_btc               6.273e-14  4.853e-14   1.293   0.1963    
day_of_weekTue          -4.382e-03  3.173e-03  -1.381   0.1674    
day_of_weekWed          -2.307e-03  3.179e-03  -0.726   0.4681    
day_of_weekThu          -5.948e-03  3.193e-03  -1.863   0.0626 .  
day_of_weekFri          -4.553e-03  3.215e-03  -1.416   0.1569    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04179 on 1768 degrees of freedom
Multiple R-squared:  0.0943,    Adjusted R-squared:  0.08918 
F-statistic: 18.41 on 10 and 1768 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>Reducing the influential observation slightly reduces the RSE. This indicates an improvement in the model’s ability to predict btc_return after accounting for outliers. The range of residuals is also slightly narrower.</p></li>
<li><p>Coefficients for bs(spy_return, df = 4) terms become more positive across all spline components in the adjusted model.</p></li>
<li><p>The intercept becomes larger and more negative after removing the influential observation. This suggests that the outlier was pulling the overall baseline estimate closer to zero.</p></li>
<li><p>Removing the influential observation amplifies the relationship between spy_return (in its nonlinear form) and btc_return. This suggests the outlier was dampening the estimated strength of this relationship.</p></li>
<li><p>Removing the influential observation improves both R-squared and adjusted R-squared values too. The change is modest, indicating that the explanatory power of the predictors remains relatively low.</p></li>
<li><p>F-statistic in the original model was 16.38, while the one without the influential observation is 18.41.</p>
<ul>
<li>The higher F-statistic in the adjusted model reflects an overall improvement in model fit and significance after removing the outlier. This further supports the robustness of the model’s conclusions in the absence of the one extreme leverage point.</li>
</ul></li>
</ul>
</section>
<section id="multicollinearity-check" class="level3">
<h3 class="anchored" data-anchor-id="multicollinearity-check"><strong>Multicollinearity Check</strong></h3>
<p>I’ll perform these checks on the new best model, model_spline_noinf.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute VIF for the spline model</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>vif_spline <span class="ot">&lt;-</span> <span class="fu">vif</span>(model_spline_noinf)</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vif_spline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           GVIF Df GVIF^(1/(2*Df))
bs(spy_return, df = 4) 1.793977  4        1.075789
volume_spy             1.794685  1        1.339658
volume_btc             1.018479  1        1.009197
day_of_week            1.028758  4        1.003550</code></pre>
</div>
</div>
<p>All predictors have very low VIF values (well below 5), confirming that multicollinearity is not a concern for this model. This ensures that the coefficients are stable and can be interpreted reliably without issues arising from excessive correlations between predictors.</p>
</section>
<section id="cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="cross-validation">Cross-Validation</h3>
<p>To estimate the leave-one-out prediction error for the spline model without the high-leverage point, we will use LOOCV. Here’s the process and interpretation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="co"># define LOOCV control</span></span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"LOOCV"</span>)</span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a><span class="co"># train the spline model using LOOCV</span></span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">888</span>) </span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a>loocv_model <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a>  btc_return <span class="sc">~</span> <span class="fu">bs</span>(spy_return, <span class="at">df =</span> <span class="dv">4</span>) <span class="sc">+</span> volume_spy <span class="sc">+</span> volume_btc <span class="sc">+</span> day_of_week,</span>
<span id="cb111-10"><a href="#cb111-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data_noinf,</span>
<span id="cb111-11"><a href="#cb111-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb111-12"><a href="#cb111-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl =</span> control</span>
<span id="cb111-13"><a href="#cb111-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb111-14"><a href="#cb111-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-15"><a href="#cb111-15" aria-hidden="true" tabindex="-1"></a><span class="co"># summarize the results</span></span>
<span id="cb111-16"><a href="#cb111-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(loocv_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

1779 samples
   4 predictor

No pre-processing
Resampling: Leave-One-Out Cross-Validation 
Summary of sample sizes: 1778, 1778, 1778, 1778, 1778, 1778, ... 
Resampling results:

  RMSE        Rsquared    MAE       
  0.04230419  0.06617877  0.02870759

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
</div>
<ul>
<li><p>RMSE (Root Mean Squared Error): 0.04230419</p>
<ul>
<li>This indicates the average prediction error in BTC daily returns is approximately 4.23%. This is close to the Residual Standard Error (RSE) of 0.04179 from the training model, suggesting good generalization.</li>
</ul></li>
<li><p>R-squared (R²): 0.06617877</p>
<ul>
<li>The LOOCV R² is slightly lower than the Adjusted R² of 0.08918 from the training model. While this shows a small drop, the difference is not large, probably suggesting the model is capturing meaningful patterns in the data without excessive overfitting.</li>
</ul></li>
<li><p>MAE (Mean Absolute Error): 0.02870759</p>
<ul>
<li>This indicates that, on average, the absolute prediction error is about 2.87%, which aligns with the RMSE and suggests the predictions are reasonably accurate.</li>
</ul></li>
</ul>
</section>
<section id="is-my-best-model-overfit" class="level3">
<h3 class="anchored" data-anchor-id="is-my-best-model-overfit">Is my best model overfit?</h3>
<p>My best model does not show signs of overfitting. Here are some reasons why:</p>
<ul>
<li><p>Comparison of RMSE and RSE:</p>
<ul>
<li>The RMSE from LOOCV (0.0423) is very similar to the RSE from the training model (0.04179). This indicates no evidence of overfitting, as the model performs comparably well on unseen data.</li>
</ul></li>
<li><p>Comparison of LOOCV R² and Adjusted R²:</p>
<ul>
<li>The LOOCV R² (0.066) is slightly lower than the Adjusted R² (0.089), but the difference is minimal. This suggests that the model generalizes well and is not overly complex.</li>
</ul></li>
</ul>
</section>
</section>
<section id="automatic-model-selection" class="level2">
<h2 class="anchored" data-anchor-id="automatic-model-selection">Automatic Model Selection</h2>
<p>I implemented backward selection using the Akaike Information Criterion, also known as AIC. This method starts with all predictors and iteratively removes the least significant variable until the model with the lowest AIC is achieved.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform backward selection on the best spline model</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>backward_model <span class="ot">&lt;-</span> <span class="fu">stepAIC</span>(model_spline_noinf, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=-11286.24
btc_return ~ bs(spy_return, df = 4) + volume_spy + volume_btc + 
    day_of_week

                         Df Sum of Sq    RSS    AIC
- day_of_week             4  0.007351 3.0946 -11290
- volume_btc              1  0.002918 3.0902 -11287
&lt;none&gt;                                3.0873 -11286
- volume_spy              1  0.004535 3.0918 -11286
- bs(spy_return, df = 4)  4  0.297822 3.3851 -11130

Step:  AIC=-11290.01
btc_return ~ bs(spy_return, df = 4) + volume_spy + volume_btc

                         Df Sum of Sq    RSS    AIC
- volume_btc              1  0.002905 3.0975 -11290
&lt;none&gt;                                3.0946 -11290
- volume_spy              1  0.003688 3.0983 -11290
- bs(spy_return, df = 4)  4  0.297174 3.3918 -11135

Step:  AIC=-11290.34
btc_return ~ bs(spy_return, df = 4) + volume_spy

                         Df Sum of Sq    RSS    AIC
- volume_spy              1  0.003165 3.1007 -11290
&lt;none&gt;                                3.0975 -11290
- bs(spy_return, df = 4)  4  0.295454 3.3930 -11136

Step:  AIC=-11290.52
btc_return ~ bs(spy_return, df = 4)

                         Df Sum of Sq    RSS    AIC
&lt;none&gt;                                3.1007 -11290
- bs(spy_return, df = 4)  4   0.30802 3.4087 -11130</code></pre>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show the final model</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(backward_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = btc_return ~ bs(spy_return, df = 4), data = data_noinf)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.188601 -0.019078 -0.002468  0.017640  0.247729 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -0.32058    0.03648  -8.788  &lt; 2e-16 ***
bs(spy_return, df = 4)1  0.28637    0.04700   6.093 1.36e-09 ***
bs(spy_return, df = 4)2  0.31578    0.03602   8.766  &lt; 2e-16 ***
bs(spy_return, df = 4)3  0.37074    0.04464   8.306  &lt; 2e-16 ***
bs(spy_return, df = 4)4  0.39536    0.04605   8.586  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04181 on 1774 degrees of freedom
Multiple R-squared:  0.09036,   Adjusted R-squared:  0.08831 
F-statistic: 44.06 on 4 and 1774 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The backward selection process removed volume_btc, volume_spy, and day_of_week from the model. This aligns with earlier findings that these predictors do not contribute significantly to explaining BTC returns.</p>
<p>The retained nonlinear terms for SPY returns (bs(spy_return, df = 4)) confirm that BTC returns are influenced by SPY returns in a nonlinear manner. This supports the hypothesis that there is a meaningful but complex relationship between traditional stock markets and cryptocurrency markets.</p>
<section id="strenghts-limitations-of-automatic-model-selection" class="level3">
<h3 class="anchored" data-anchor-id="strenghts-limitations-of-automatic-model-selection">Strenghts &amp; Limitations of automatic model selection</h3>
<p>Generally speaking:</p>
<ul>
<li><p><strong>Strengths:</strong></p>
<ul>
<li><p>The backward selection process simplified the model by removing predictors with minimal contribution, improving interpretability.</p></li>
<li><p>AIC ensured that the selected model balances goodness-of-fit with parsimony (keeping things as simple as possible while still being effective), avoiding unnecessary complexity.</p></li>
</ul></li>
<li><p><strong>Limitations:</strong></p>
<ul>
<li><p>The automated process does not account for the research context or prior knowledge of variables’ importance.</p></li>
<li><p>p-values in the final model may be inflated due to multiple comparisons during the selection process (will have a subsection dedicated to this later).</p></li>
<li><p>The backward-selected model only optimizes AIC for this specific dataset, and results may not generalize to other datasets.</p></li>
</ul></li>
</ul>
</section>
<section id="impact-automatic-model-selection-has-on-p-values-obtained-from-the-final-model" class="level3">
<h3 class="anchored" data-anchor-id="impact-automatic-model-selection-has-on-p-values-obtained-from-the-final-model">Impact Automatic Model Selection has on P-values obtained from the final model</h3>
<p>Automatic model selection, such as what I used in backward selection, impact the p-values of the final model by increasing the risk of p-value inflation due to multiple comparisons made during the selection process. This means the retained predictors might appear more significant than they truly are because the process repeatedly tests and evaluates subsets of predictors. Additionally, the p-values are dataset-specific and may not generalize well to new data or contexts. While the selection improves model parsimony and interpretability, it compromises the strict validity of the p-values.</p>
</section>
</section>
<section id="conclusions-final-thoughts" class="level2">
<h2 class="anchored" data-anchor-id="conclusions-final-thoughts">Conclusions &amp; Final Thoughts</h2>
<section id="what-i-have-learned-after-engaging-in-this-process" class="level3">
<h3 class="anchored" data-anchor-id="what-i-have-learned-after-engaging-in-this-process">What I have Learned after Engaging in this Process</h3>
<p>I learned a lot more about R and became more familiar with qmd files. I also learned how much work it is to work with numbers like this; it is a lot. At the beginning, I had such a big scope set and slowly towards the end I had to make that scope smaller.</p>
</section>
<section id="most-interesting-relevant-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="most-interesting-relevant-conclusions">Most interesting &amp; relevant conclusions</h3>
<p>Some notable ones:</p>
<ul>
<li><p>The Monday effect that has been around for many, many years does not seem to be prevalent in our smaller date time frame. I thought for sure this would show up here.</p></li>
<li><p>There are no highly significant “best” days of the week to trade crypto.</p></li>
<li><p>The correlation between SPY and BTC exists and is real. It is very much non-linear and would take lots of time to get closer to perfection. The sporadic nature of crypto does not help when making these models.</p></li>
<li><p>I come from a Python-heavy background; I prefer it so much more than R Studio. I’m not sure if this is an unpopular opinion, but Python to me has more flexibility and even more things you can do (perhaps I think this because I’m newer to R Studio).</p></li>
</ul>
</section>
<section id="future-avenues-for-research" class="level3">
<h3 class="anchored" data-anchor-id="future-avenues-for-research">Future Avenues for Research</h3>
<p>I merely scratched the surface. Using data science &amp; algorithms to analyze the stock and crypto market is very common, yet there is so much that goes into it. There are so many external variables that can be tested that most probably have effects on this relationship. Something that can be explored (I had no time) is correlations between SPY and cryptocurrency volumes when under different lags. Additionally, simply adding more variables could help such as macroeconomic indicators, sentiment analysis, etc.. Also, exploring more tickers as well as more cryptocurrencies would probably be insightful.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>